#!/bin/bash
set -euo pipefail

# Local installer for Call Recorder.
# Creates deploy/.env and deploy/docker-compose.local.yml, then builds and
# starts the Docker Compose stack. Run this from the repository root.
#
# Supports two modes:
#   1. Deploy a local PostgreSQL container (default).
#   2. Connect to an existing PostgreSQL server.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
DEPLOY_DIR="$PROJECT_ROOT/deploy"

REPO_URL="https://github.com/renfrewcountyscanner/call-recorder.git"

die() {
  echo "$1" >&2
  exit 1
}

require() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed."
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64
  fi
}

detect_compose() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
  elif docker-compose version >/dev/null 2>&1; then
    echo "docker-compose"
  else
    die "Neither 'docker compose' nor 'docker-compose' is available."
  fi
}

resolve_path() {
  local path="$1"
  if [ "${path:0:1}" != "/" ]; then
    path="$PROJECT_ROOT/$path"
  fi
  mkdir -p "$path" || die "Cannot create directory: $path"
  (cd "$path" && pwd)
}

# Ensure we are in the repository root.
if [ ! -f "$DEPLOY_DIR/docker-compose.yml" ]; then
  die "Cannot find deploy/docker-compose.yml. Run this script from the call-recorder repository root."
fi

require git
require docker
COMPOSE="$(detect_compose)"

echo "=== Call Recorder local installer ==="
echo

# If not already inside a git repo, clone it.
if [ ! -d "$PROJECT_ROOT/.git" ]; then
  echo "This does not appear to be a git checkout."
  read -rp "Clone from $REPO_URL into $PROJECT_ROOT? [Y/n] " clone_choice
  clone_choice="${clone_choice:-Y}"
  if [[ "$clone_choice" =~ ^[Yy]$ ]]; then
    git clone "$REPO_URL" "$PROJECT_ROOT"
  else
    die "Please run this script from a call-recorder git checkout."
  fi
fi

# Pull latest changes if this is a git checkout.
if [ -d "$PROJECT_ROOT/.git" ]; then
  echo "Fetching latest changes from GitHub..."
  git -C "$PROJECT_ROOT" fetch origin
  CURRENT_BRANCH="$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD)"
  git -C "$PROJECT_ROOT" pull origin "$CURRENT_BRANCH" || true
fi

# PostgreSQL mode.
read -rp "Deploy a local PostgreSQL container? [Y/n] " LOCAL_POSTGRES
LOCAL_POSTGRES="${LOCAL_POSTGRES:-Y}"

if [[ "$LOCAL_POSTGRES" =~ ^[Yy]$ ]]; then
  DEPLOY_POSTGRES="true"
else
  DEPLOY_POSTGRES="false"
fi

# Audio storage path.
DEFAULT_AUDIO="$PROJECT_ROOT/runtime/audio"
read -rp "Directory to store call recordings [$DEFAULT_AUDIO]: " AUDIO_PATH
AUDIO_PATH="$(resolve_path "${AUDIO_PATH:-$DEFAULT_AUDIO}")"

# Secrets path.
DEFAULT_SECRETS="$PROJECT_ROOT/runtime/secrets"
read -rp "Directory to store encrypted secrets [$DEFAULT_SECRETS]: " SECRETS_PATH
SECRETS_PATH="$(resolve_path "${SECRETS_PATH:-$DEFAULT_SECRETS}")"

# External port.
read -rp "External HTTP port for the web UI [8080]: " EXTERNAL_PORT
EXTERNAL_PORT="${EXTERNAL_PORT:-8080}"

# Administration.
read -rp "Enable local admin token mode? [Y/n] " ADMIN_ENABLE
ADMIN_ENABLE="${ADMIN_ENABLE:-Y}"
if [[ "$ADMIN_ENABLE" =~ ^[Yy]$ ]]; then
  ADMIN_ENABLED="true"
  read -rp "Admin token (leave blank to generate a random one): " ADMIN_TOKEN
  ADMIN_TOKEN="${ADMIN_TOKEN:-$(generate_secret)}"
else
  ADMIN_ENABLED="false"
  ADMIN_TOKEN="$(generate_secret)"
fi

# Generate remaining secrets.
SENDER_KEY="$(generate_secret)"

ENV_FILE="$DEPLOY_DIR/.env"
LOCAL_COMPOSE="$DEPLOY_DIR/docker-compose.local.yml"

if [ -f "$ENV_FILE" ]; then
  echo
  echo "WARNING: $ENV_FILE already exists."
  read -rp "Overwrite it? [y/N] " OVERWRITE
  OVERWRITE="${OVERWRITE:-N}"
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    die "Aborted. Existing $ENV_FILE kept."
  fi
fi

# Build environment file and local override based on PostgreSQL mode.
if [ "$DEPLOY_POSTGRES" = "true" ]; then
  # Local PostgreSQL.
  DEFAULT_POSTGRES="$PROJECT_ROOT/runtime/postgres"
  read -rp "Directory to store PostgreSQL data [$DEFAULT_POSTGRES]: " POSTGRES_PATH
  POSTGRES_PATH="$(resolve_path "${POSTGRES_PATH:-$DEFAULT_POSTGRES}")"

  POSTGRES_PASSWORD="$(generate_secret)"

  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file private and do not commit it.

CALL_RECORDER_LISTEN_ADDRESS=0.0.0.0
CALL_RECORDER_LISTEN_PORT=8080
CALL_RECORDER_DATABASE_URL=postgresql://call_recorder:${POSTGRES_PASSWORD}@postgres:5432/call_recorder?sslmode=disable
CALL_RECORDER_AUDIO_ROOT=/var/lib/call-recorder/audio
CALL_RECORDER_RETENTION_DAYS=60
CALL_RECORDER_DUPLICATE_START_TOLERANCE_MS=2000
CALL_RECORDER_DUPLICATE_DURATION_TOLERANCE_MS=300

POSTGRES_DB=call_recorder
POSTGRES_USER=call_recorder
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

CALL_RECORDER_PORT=${EXTERNAL_PORT}
CALL_RECORDER_BOOTSTRAP_SENDER_ID=example-sender
CALL_RECORDER_BOOTSTRAP_SENDER_KEY=${SENDER_KEY}

CALL_RECORDER_ADMIN_ENABLED=${ADMIN_ENABLED}
CALL_RECORDER_ADMIN_OPEN=false
CALL_RECORDER_ADMIN_TOKEN=${ADMIN_TOKEN}

CALL_RECORDER_CLOUDFLARE_ACCESS_ENABLED=false
CALL_RECORDER_CLOUDFLARE_ADMIN_EMAIL=
CALL_RECORDER_CLOUDFLARE_TRUSTED_PROXY_IPS=
EOF

  cat > "$LOCAL_COMPOSE" <<EOF
# Auto-generated by install.sh. Binds host paths chosen during installation.
# This file is ignored by Git.
services:
  postgres:
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
  audio-init:
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets
  backend:
    ports:
      - "${EXTERNAL_PORT}:8080"
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets
  transcription-worker:
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio:ro
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets:ro
EOF

  COMPOSE_FILES="-f $DEPLOY_DIR/docker-compose.yml -f $LOCAL_COMPOSE"
else
  # Existing PostgreSQL server.
  echo
  echo "=== Existing PostgreSQL connection ==="
  read -rp "PostgreSQL host or IP: " PG_HOST
  [ -z "$PG_HOST" ] && die "PostgreSQL host is required."
  read -rp "PostgreSQL port [5432]: " PG_PORT
  PG_PORT="${PG_PORT:-5432}"
  read -rp "PostgreSQL database name [call_recorder]: " PG_DB
  PG_DB="${PG_DB:-call_recorder}"
  read -rp "PostgreSQL user [call_recorder]: " PG_USER
  PG_USER="${PG_USER:-call_recorder}"
  read -rsp "PostgreSQL password: " PG_PASSWORD
  echo
  [ -z "$PG_PASSWORD" ] && die "PostgreSQL password is required."
  read -rp "PostgreSQL SSL mode [disable]: " PG_SSLMODE
  PG_SSLMODE="${PG_SSLMODE:-disable}"

  DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=${PG_SSLMODE}"

  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Keep this file private and do not commit it.

CALL_RECORDER_LISTEN_ADDRESS=0.0.0.0
CALL_RECORDER_LISTEN_PORT=8080
CALL_RECORDER_DATABASE_URL=${DATABASE_URL}
CALL_RECORDER_AUDIO_ROOT=/var/lib/call-recorder/audio
CALL_RECORDER_RETENTION_DAYS=60
CALL_RECORDER_DUPLICATE_START_TOLERANCE_MS=2000
CALL_RECORDER_DUPLICATE_DURATION_TOLERANCE_MS=300

# External PostgreSQL server is used; local postgres container is not started.
# POSTGRES_DB=
# POSTGRES_USER=
# POSTGRES_PASSWORD=

CALL_RECORDER_PORT=${EXTERNAL_PORT}
CALL_RECORDER_BOOTSTRAP_SENDER_ID=example-sender
CALL_RECORDER_BOOTSTRAP_SENDER_KEY=${SENDER_KEY}

CALL_RECORDER_ADMIN_ENABLED=${ADMIN_ENABLED}
CALL_RECORDER_ADMIN_OPEN=false
CALL_RECORDER_ADMIN_TOKEN=${ADMIN_TOKEN}

CALL_RECORDER_CLOUDFLARE_ACCESS_ENABLED=false
CALL_RECORDER_CLOUDFLARE_ADMIN_EMAIL=
CALL_RECORDER_CLOUDFLARE_TRUSTED_PROXY_IPS=
EOF

  cat > "$LOCAL_COMPOSE" <<EOF
# Auto-generated by install.sh. Binds host paths chosen during installation.
# This file is ignored by Git.
services:
  audio-init:
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets
  backend:
    ports:
      - "${EXTERNAL_PORT}:8080"
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets
  transcription-worker:
    volumes:
      - ${AUDIO_PATH}:/var/lib/call-recorder/audio:ro
      - ${SECRETS_PATH}:/var/lib/call-recorder/secrets:ro
EOF

  COMPOSE_FILES="-f $DEPLOY_DIR/docker-compose.external-postgres.yml -f $LOCAL_COMPOSE"
fi

chmod 600 "$ENV_FILE"

# Ensure .gitignore will ignore generated local files.
if ! grep -q "docker-compose.local.yml" "$PROJECT_ROOT/.gitignore" 2>/dev/null; then
  echo "deploy/docker-compose.local.yml" >> "$PROJECT_ROOT/.gitignore"
fi

echo
echo "=== Configuration written ==="
echo "  .env file:              $ENV_FILE"
echo "  Local compose override: $LOCAL_COMPOSE"
echo "  Call recordings path:   $AUDIO_PATH"
echo "  Secrets path:           $SECRETS_PATH"
echo "  External port:          $EXTERNAL_PORT"
echo "  Admin enabled:          $ADMIN_ENABLED"
if [ "$ADMIN_ENABLED" = "true" ]; then
  echo "  Admin token:            ${ADMIN_TOKEN}"
fi
echo "  Bootstrap sender key:   ${SENDER_KEY}"
echo "  PostgreSQL mode:        $([ "$DEPLOY_POSTGRES" = "true" ] && echo 'local container' || echo 'external server')"
if [ "$DEPLOY_POSTGRES" = "true" ]; then
  echo "  PostgreSQL data path:   $POSTGRES_PATH"
fi
echo

echo "=== Validating Docker Compose configuration ==="
$COMPOSE $COMPOSE_FILES --env-file "$ENV_FILE" config -q

echo "=== Building and starting services ==="
GIT_COMMIT="$(git -C "$PROJECT_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
export GIT_COMMIT BUILD_TIME
$COMPOSE $COMPOSE_FILES --env-file "$ENV_FILE" up -d --build --remove-orphans

echo "=== Waiting for backend to become healthy ==="
for i in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${EXTERNAL_PORT}/healthz" >/dev/null 2>&1; then
    echo "Backend is healthy."
    break
  fi
  sleep 1
done

if ! curl -fsS "http://127.0.0.1:${EXTERNAL_PORT}/healthz" >/dev/null 2>&1; then
  die "Backend did not become healthy within 60 seconds. Check logs with: $COMPOSE $COMPOSE_FILES logs backend"
fi

echo
echo "=== Call Recorder is installed and running ==="
echo "  Web UI:     http://127.0.0.1:${EXTERNAL_PORT}/"
echo "  Health:     http://127.0.0.1:${EXTERNAL_PORT}/healthz"
echo "  Admin:      http://127.0.0.1:${EXTERNAL_PORT}/admin/login"
echo
echo "Next steps:"
echo "  - Review $ENV_FILE and keep it secure."
if [ "$DEPLOY_POSTGRES" != "true" ]; then
  echo "  - Apply the migrations in backend/migrations/ to your external database."
  echo "    Example: psql -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DB -f backend/migrations/001_initial.sql"
fi
echo "  - Configure a sender with the bootstrap sender key above or create a new one via /admin/senders."
echo "  - Backups: $PROJECT_ROOT/deploy/backup.sh DESTINATION_DIRECTORY"
echo "  - Logs:    $COMPOSE $COMPOSE_FILES logs -f"
echo
